server:
  port: 8888
eureka: 
  instance: 
    hostname: 127.0.0.1
  client: 
    registerWithEureka: false #indecate that this service is Eureka server.
    fetchRegistry: false #indecate that this service is Eureka server.
    serviceUrl: 
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/