--- 
app: 
  complexList: 
    - 
      a1: a1
      a2: a2
      a3: a3
    - 
      b1: b1
      b2: b2
      b3: b3
    - 
      c1: c1
      c2: c2
      c3: c3
  complexMap: 
    key1: 
      - v11
      - v22
      - v33
    key2: 
      - v1
      - v2
      - v3
  list: 
    - ab
    - bc
    - cd
  map: 
    a: a11
    b: b11
    c: 
      - a1
      - a2
k1:
  k2:
    k3: "some value will be filled here"
server: 
  port: 8888
spring:
  activemq:
    #failover:(tcp://localhost:61616,tcp://localhost:61617) 
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: true
      maxConnections: 10
sendmsg:
  scheduled:
    time: 2000
      